from __future__ import annotations

from types import MappingProxyType
from typing import Mapping


OWNER_ECONOMIC_AUTHORITY_UK_UA: Mapping[str, str] = MappingProxyType(
    {
        "ui.windows.owner_authority.frame.title": "Економічні межі власника",
        "ui.windows.owner_authority.button.open": "Переглянути економічні межі власника",
        "ui.windows.owner_authority.button.create": "Перевірити та створити початковий контракт",
        "ui.windows.owner_authority.button.close": "Закрити",
        "ui.windows.owner_authority.dialog.title": "Економічні межі власника",
        "ui.windows.owner_authority.dialog.form.title": "Початковий контракт власника",
        "ui.windows.owner_authority.dialog.review.title": "Підтвердити початковий контракт",
        "ui.windows.owner_authority.dialog.review.body": "Буде створено лише початковий контракт. Після збереження ця поверхня не змінює й не замінює його. Перевірте межі у списку та підтвердьте створення.",
        "ui.windows.owner_authority.accessibility.open.name": "Економічні межі власника",
        "ui.windows.owner_authority.accessibility.open.description": "Відкриває лише читання поточного контракту або форму одноразового початкового створення.",
        "ui.windows.owner_authority.accessibility.status.name": "Стан економічних меж власника",
        "ui.windows.owner_authority.accessibility.status.description": "Лише для читання: відсутній, дійсний або пошкоджений контракт економічної цілі.",
        "ui.windows.owner_authority.accessibility.readback.name": "Точні економічні межі власника",
        "ui.windows.owner_authority.accessibility.readback.description": "Список лише для читання з ідентичністю, межами, автоматизацією, аварійною зупинкою та списками заборон.",
        "ui.windows.owner_authority.accessibility.create.name": "Створити початковий економічний контракт",
        "ui.windows.owner_authority.accessibility.create.description": "Спочатку перевіряє типізовані значення та вимагає явного підтвердження. Існуючий контракт не змінюється.",
        "ui.windows.owner_authority.state.absent": "Економічний контракт власника ще не створено.",
        "ui.windows.owner_authority.state.valid": "Економічний контракт власника дійсний і доступний лише для читання.",
        "ui.windows.owner_authority.state.corrupt": "Економічний контракт власника пошкоджений або недійсний; запис заблоковано.",
        "ui.windows.owner_authority.boundary.initial_only": "Можна лише явно створити перший типізований контракт після перегляду та підтвердження.",
        "ui.windows.owner_authority.boundary.read_only": "Зміна, видалення або заміна існуючого контракту тут не реалізована і не виконується.",
        "ui.windows.owner_authority.boundary.corrupt": "Відновіть збереження через окрему контрольовану процедуру; ця поверхня не перезаписує пошкоджені дані.",
        "ui.windows.owner_authority.none": "немає",
        "ui.windows.owner_authority.readback.identity": "Ціль: {goal_id}; ревізія: {revision}",
        "ui.windows.owner_authority.readback.bankroll": "Банк: {bankroll_id}; валюта: {currency}",
        "ui.windows.owner_authority.readback.objective": "Економічна ціль: довгострокове зростання паперового банку з урахуванням ризику",
        "ui.windows.owner_authority.readback.limit": "{name}: {value}",
        "ui.windows.owner_authority.readback.automation": "Стеля автоматизації: {level}; аварійна STOP: {emergency_stop}",
        "ui.windows.owner_authority.readback.restrictions": "{name}: {values}",
        "ui.windows.owner_authority.error.text": "Поле «{field}» має бути текстом.",
        "ui.windows.owner_authority.error.required": "Заповніть поле «{field}» без початкових чи кінцевих пробілів.",
        "ui.windows.owner_authority.error.decimal": "Поле «{field}» має бути скінченним канонічним десятковим числом.",
        "ui.windows.owner_authority.error.integer": "Поле «{field}» має бути додатним цілим числом.",
        "ui.windows.owner_authority.error.duplicates": "Поле «{field}» не може містити повторів.",
        "ui.windows.owner_authority.error.missing": "Відсутні обов’язкові поля контракту: {fields}.",
        "ui.windows.owner_authority.error.automation": "Стеля автоматизації має бути цілим значенням від 0 до 4.",
        "ui.windows.owner_authority.error.contract": "Початковий контракт відхилено типізованою перевіркою меж.",
        "ui.windows.owner_authority.error.not_absent": "Початковий контракт можна створити лише коли збереження відсутнє; поточний стан не дає права на запис.",
        "ui.windows.owner_authority.error.confirmation": "Створення скасовано: потрібне явне підтвердження власника.",
        "ui.windows.owner_authority.error.persist": "Початковий контракт не збережено; стан запису не підтверджений.",
        "ui.windows.owner_authority.error.readback": "Після запису неможливо підтвердити точний контракт; подальші дії зупинено.",
        "ui.windows.owner_authority.error.strategy_blocked": "Спершу виберіть і повністю налаштуйте типізовану дослідницьку стратегію з планом; базова та спостережна стратегії не мають доведеного розміру ставки з економічною ціллю.",
        "ui.windows.owner_authority.error.busy": "Створення економічного контракту заблоковане, поки триває відтворення, спостереження, перевірка даних або відновлення.",
        "ui.windows.owner_authority.error.cancelled": "Створення початкового контракту скасовано без запису.",
        "ui.windows.owner_authority.field.goal_id": "Ідентифікатор цілі",
        "ui.windows.owner_authority.field.bankroll_id": "Ідентифікатор банку",
        "ui.windows.owner_authority.field.currency": "Валюта (3 великі латинські літери)",
        "ui.windows.owner_authority.field.max_stake_fraction": "Максимальна частка однієї ставки",
        "ui.windows.owner_authority.field.max_stake_amount": "Максимальна сума однієї ставки (порожньо — без абсолютної межі)",
        "ui.windows.owner_authority.field.max_session_loss_fraction": "Максимальна втрата сесії",
        "ui.windows.owner_authority.field.max_day_loss_fraction": "Максимальна денна втрата",
        "ui.windows.owner_authority.field.max_drawdown_fraction": "Максимальна просадка",
        "ui.windows.owner_authority.field.max_capital_at_risk_fraction": "Максимальний капітал під ризиком",
        "ui.windows.owner_authority.field.max_event_concentration_fraction": "Максимальна концентрація події",
        "ui.windows.owner_authority.field.max_market_concentration_fraction": "Максимальна концентрація ринку",
        "ui.windows.owner_authority.field.max_provider_concentration_fraction": "Максимальна концентрація постачальника",
        "ui.windows.owner_authority.field.max_sport_concentration_fraction": "Максимальна концентрація спорту",
        "ui.windows.owner_authority.field.max_turnover_fraction": "Максимальна частка обороту",
        "ui.windows.owner_authority.field.max_risk_of_ruin": "Максимальний ризик руйнування",
        "ui.windows.owner_authority.field.max_execution_slippage_fraction": "Максимальне прослизання виконання",
        "ui.windows.owner_authority.field.max_quote_age_seconds": "Максимальний вік котирування, секунд",
        "ui.windows.owner_authority.field.minimum_data_quality": "Мінімальна якість даних",
        "ui.windows.owner_authority.field.max_concurrent_positions": "Максимум одночасних позицій",
        "ui.windows.owner_authority.field.max_parlay_legs": "Максимум подій у парлеї",
        "ui.windows.owner_authority.field.automation_level": "Стеля автоматизації (0–4)",
        "ui.windows.owner_authority.field.blocked_sports": "Заборонені види спорту (через кому)",
        "ui.windows.owner_authority.field.blocked_providers": "Заборонені постачальники (через кому)",
        "ui.windows.owner_authority.field.blocked_markets": "Заборонені ринки (через кому)",
        "ui.windows.owner_authority.field.emergency_stop": "Аварійна STOP",
    }
)
